### ISSUE TITLE
Issue spawning URDF bot

### ISSUE THREAD

**Issue by huckl3b3rry87** [mitchellspryn/UrdfSim#19]
I followed the tutorials for AirSim and URDF sim, but I am having an issue trying to spawn a URDF bot into Unreal. 

It seems that there are no Blueprints for the URDF model, so I tried to simply drag and drop it from the Window in the picture into the Unreal editor, but nothing seems to show up

![ex](https://user-images.githubusercontent.com/8204378/81623741-39ff2500-93a9-11ea-99da-bc38681e14d6.PNG)

Sorry, I am a newbie to Unreal. Thank you for any help or advice

**Comment by mitchellspryn** [comment]
The bot is a C++ class, not a blueprint class. All you should have to do is drag a player start into the level and set the game mode to "AirSimGameMode." Then, assuming that your URDF file / settings are correct, it should spawn.

**Comment by huckl3b3rry87** [comment]
@mitchellspryn thank you for your patience and quick explanation:) Your suggestion worked!wwwwwwwwwwwwwwwwwww
