### ISSUE TITLE
getting the robot states

### ISSUE THREAD

**Issue by huckl3b3rry87** [mitchellspryn/UrdfSim#22]
I am interested in getting [the robot states](http://wiki.ros.org/urdf/Tutorials/Using%20urdf%20with%20robot_state_publisher).

So, for instance, in the case of the [Arm](https://github.com/mitchellspryn/UrdfSim/blob/master/docs/images/Arm.gif), these states include the joint angles and the position of the prismatic joint of the grippers.

For reference, I am interested in doing some closed loop, probably PID control to move the arm to a particular location and picking it up and moving it.

Thank you!

**Comment by huckl3b3rry87** [comment]
Sorry, I think that I found it `` getUrdfBotState``.

**Comment by mitchellspryn** [comment]
For anyone coming from google, yes, that is the API call to use.
