### ISSUE TITLE
motion planning and control backend

### ISSUE THREAD

**Issue by huckl3b3rry87** [mitchellspryn/UrdfSim#23]
Correct me if I am wrong, but it seems that there is no API or backend available to do motion planning and control, for instance in ROS, there is [moveit](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/urdf_srdf/urdf_srdf_tutorial.html). 

I am interested in setting the position of the gripper, of the Arm URDF, so that I can pick up an object and move it around. To accomplish this, I will need to do trajectory/motion planning (maybe just inverse kinematics) and then trajectory following (low level control like PID) for each joint. 

While I will enjoy writing this kind of code, time is a constraint for me and I was wondering if you had any ideas for backends that we may be able to establish for doing such a tasks.

**Comment by mitchellspryn** [comment]
There is nothing like that built into UrdfSim. 

MoveIt is good. Writing a ros node to publish data from your bot into ROS should be pretty easy. 

[The Open Motion Planning Library](https://ompl.kavrakilab.org/) might be of interest to you as well.

**Comment by huckl3b3rry87** [comment]
@mitchellspryn thank you very much for the advice!
