### ISSUE TITLE
Issue controlling gripper in RobotArm.xml

### ISSUE THREAD

**Issue by huckl3b3rry87** [mitchellspryn/UrdfSim#24]
I am trying to control the manipulator to open or close using functionality from ArmClientTest.py i.e.,

```
print('Closing claw')
client.set_manipulator(0)
```
or 
```
print('Opening claw')
client.set_manipulator(1)
```

But it is not moving the manipulator arms.
![A](https://user-images.githubusercontent.com/8204378/82496835-2edf7f80-9aa2-11ea-8c39-8ec07442f859.PNG)

I am able to use the PythonClient to move the URDF around to a random pose.

**Q1**: Any thoughts? 

**Q2**: Eventually, I would like to be able to grab this cup (or some object) and move it around. Is this easily done once I can grab the cup? 

Thank you!

**Comment by huckl3b3rry87** [comment]
Also, I went back to the default URDF for this robot ( I had modified a couple things), but I am still getting the issue
![Capture](https://user-images.githubusercontent.com/8204378/82509099-cbfae200-9abb-11ea-9645-2dbf4685e979.PNG)

**Comment by huckl3b3rry87** [comment]
It seems to be an issue with the prismatic joint, if I change 
```
  <joint name="manipulator_base_to_right_manipulator" type="prismatic">
    <parent link="manipulator_base"/>
    <child link="right_manipulator"/>
    <origin rpy="0 0 0" xyz="0 -0.085 0.065"/>
    <axis rpy="0 0 0" xyz="0 -1 0"/>
    <limit lower="-0.070" upper="0" effort="10000" velocity="0.2"/>
  </joint>
```
to 
```
  <joint name="manipulator_base_to_right_manipulator" type="revolute">
    <parent link="manipulator_base"/>
    <child link="right_manipulator"/>
    <origin rpy="0 0 0" xyz="0 -0.085 0.065"/>
    <axis rpy="0 0 0" xyz="1 0 0"/>
    <limit lower="-1.57079" upper="1.57079" effort="10000" velocity="0.2"/>
  </joint>
```
then, when the simulation starts, it looks like this 
![A](https://user-images.githubusercontent.com/8204378/82598740-f7370d00-9b5f-11ea-8b44-6efd3e0f42f4.PNG)

then sending
```
 client.set_manipulator(0)
```
rotates the right claw as 

![B](https://user-images.githubusercontent.com/8204378/82598761-fc945780-9b5f-11ea-98d2-a2305c489fc2.PNG)

**Comment by huckl3b3rry87** [comment]
Q2: Eventually, I would like to be able to grab this cup (or some object) and move it around. Is this easily done once I can grab the cup? 

A2: yes

**Comment by mitchellspryn** [comment]
This is truely bizarre. I tried it on my box just now. Everything seems to work as I would expect it to. A thought - did you rotate the playerstart from 0 degrees?

**Comment by huckl3b3rry87** [comment]
Just started from a fresh install and the gripper is closing, I did not test the rotate playerstart in this new version. 

If I have future issues, I will comment here

Thanks!
