### ISSUE TITLE
Simulation of a Truck-Trailer Systems

### ISSUE THREAD

**Issue by rachillesf** [mitchellspryn/UrdfSim#25]
Hi, thanks for the awesome contribution!

Is it possible to simulate car-like vehicles with more advanced kinematics such as truck-trailer systems, given that the system can be described by continuous joints linking 2 vehicles?

**Comment by mitchellspryn** [comment]
See my response [here](https://github.com/microsoft/AirSim/issues/1864#issuecomment-633310785).

**Comment by rachillesf** [comment]
thanks
