### ISSUE TITLE
How Can I make movement of my RunaBot? 

### ISSUE THREAD

**Issue by guldamkwak3114** [mitchellspryn/UrdfSim#34]
I manaed to import my Rubabot to the Three Bridges environment but have no idea how to let them move. How Can I let them move? 

![RUNABOT](https://user-images.githubusercontent.com/65904372/107924844-f7f9b400-6fb6-11eb-8cfc-640a831fdae6.png)

**Comment by mitchellspryn** [comment]
You'll need to use the API, either via C++ or python. [Here are some examples](https://github.com/mitchellspryn/UrdfSim/tree/master/PythonClient/urdfbot). [Here is the one relevant to the lunabot](https://github.com/mitchellspryn/UrdfSim/blob/master/PythonClient/urdfbot/LunabotClientTest.py).

**Comment by guldamkwak3114** [comment]
Can I use xbox controller, like in the case of quadrotor in Airism?

**Comment by mitchellspryn** [comment]
Sure, but you'll have to write the code to map button presses to API actions. 

URDFSim cannot provide this functionality "out-of-the-box", because we don't know a-priori what your robot looks like.
