### ISSUE TITLE
eigen has migrated and setup.sh errors out

### ISSUE THREAD

**Issue by ajberlier** [mitchellspryn/UrdfSim#4]

**Comment by ajberlier** [comment]
The github mirror works:
https://github.com/eigenteam/eigen-git-mirror/archive/3.3.2.zip

Just replace the bitbucket path with the above path in setup.sh.

**Comment by mitchellspryn** [comment]
Thanks for letting me know! I'm planning on doing an update that will make this compatible with 4.23, so I'll roll this fix into it. Is this the same issue as #3 ?
