### ISSUE TITLE
Visual Studio Updates Internal Compile Error Fix

### ISSUE THREAD

**Issue by ajberlier** [mitchellspryn/UrdfSim#5]
I had to make these modifications for build.cmd to work.

https://github.com/microsoft/AirSim/pull/1558/commits/e66190259ef6938e5506ed38485cc2e53712b061

**Comment by mitchellspryn** [comment]
What unreal engine version are you using / VS version?

So far, the code here only works on 4.18. I am currently working on updating it for 4.23, which will include this fix among others.

**Comment by ajberlier** [comment]
Unreal 4.18
VS-2017 15.9.17

**Comment by mitchellspryn** [comment]
Yes, this is a known issue with 15.9. Your fix is correct. 

In a few weeks, when I get all of the changes finalized for 4.23 (or 4.24 if it comes out), this fix will be part of it.
