### ISSUE TITLE
Materials for Custom STLs

### ISSUE THREAD

**Issue by InfraredLaser** [mitchellspryn/UrdfSim#52]
When trying to set the path for a custom material I noticed that it does not get applied to my custom STL mesh. When ends up showing is a default grey material. When looking through the issues I noticed that in #15 applying materials to custom STLs does not seem to work. Has this issue been fixed?

Here are the paths I used  to set up custom materials:
<img width="738" alt="material_issue" src="https://user-images.githubusercontent.com/60621716/124978784-10f71600-dfe7-11eb-870d-730ca0ff9d7f.PNG">

Here is a sample mesh that shows only the default grey material.
<img width="518" alt="joint_origin_offsetX-Z_01_018" src="https://user-images.githubusercontent.com/60621716/124978920-3dab2d80-dfe7-11eb-8aa6-e87013ac7429.PNG">

**Comment by InfraredLaser** [comment]
@mitchellspryn 

I am trying a potential solution to this issue. Is it possible to add materials to custom ascii STLs if the STLs are first imported as static meshes in unreal engine, then linked using the xml file?

Essentially, the process would be:
1) Import the ascii STL as an FBX file
2) In the XML, use mesh type "unreal_mesh" then point to the appropriate path to the mesh
3) Use the "material" tag to point to the location of the material in UE to attach to the mesh

**Comment by mitchellspryn** [comment]
Sorry, missed this the first time. 

If you can import it into unreal, that's definitely the way to go. In addition to being simpler at runtime, you'll get the benefits of pre-baked lighting for the mesh textures, so it will look better.

**Comment by InfraredLaser** [comment]
Thanks @mitchellspryn ,

I tried to find the example to link the unreal meshes in the XML, but the only file that exists in the example folder is just the settings-mesh.json file. 
How can we link unreal meshes in the XML and what would the appropriate file path look like?

**Comment by mitchellspryn** [comment]
[Try this](https://github.com/mitchellspryn/RoboMagellanOrchestrator/blob/master/RoboMagellanOrchestrator/rm_bot_client/RoboMagellanBot.xml#L38)

**Comment by InfraredLaser** [comment]
The above method works. Importing the STL's to UE is the way to go. 
Additionally, using this method I am able to change the materials on my meshes though UE instead of the XML giving me greater flexibility over custom meshes.
