### ISSUE TITLE
Can't find Block.sln file

### ISSUE THREAD

**Issue by Ishira1601** [mitchellspryn/UrdfSim#9]
Quite an unusual problem. I built this package the same way I did the AirSim package. Then I tried to build the Blocks environment the same way I did the AirSim Blocks environment. 
https://github.com/mitchellspryn/UrdfSim/blob/master/docs/unreal_blocks.md
However I don't get the Blocks.sln file.

**Comment by mitchellspryn** [comment]
There are no environments that come pre-built with the plugin. You need to create your own uproj and install the plugin. Blocks is not supported.

If you really want something pre-built, you may consider taking a look at [this](https://github.com/mitchellspryn/AnnotatedUnrealMaps).
